modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
modId="beyond_planets_core"
version="${file.jarVersion}"
displayName="Beyond Planets - Core"
credits="TheRealM18"
authors="The Realm 18 Studios"
description='''
This mod for the core of Beyond Planets.
'''

[[dependencies.beyond_planets_core]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_planets_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_planets_core]]
    modId="beyond_earth"
    mandatory=true
    versionRange="[6.3,)"
    ordering="AFTER"
    side="BOTH"