modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="beyond_planets_core"
version="${file.jarVersion}"
displayName="Beyond Planets - Core"
credits="The Realm18 Studios"
authors="The Realm18 Studios"
description='''
This mod for the core of Beyond Planets.
'''

[[dependencies.beyond_planets_core]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.51,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_planets_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_planets_core]]
    modId="beyond_earth"
    mandatory=false
    versionRange="[6.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.beyond_planets_core]]
    modId="futurepack"
    mandatory=false
    versionRange="[33.0,)"
    ordering="AFTER"
    side="BOTH"